spring.application.name=pagamentos
server.servlet.context-path=/pagamentos-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pagamentosapi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hibernate Envers
spring.jpa.properties.org.hibernate.envers.default_schema=auditoria
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_AUD
spring.jpa.properties.org.hibernate.envers.revision_field_name=rev
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revtype
