spring.application.name=pagamentos
server.servlet.context-path=/pagamentos-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pagamentosapi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
